

# This file was *autogenerated* from the file solve.sage
from sage.all_cmdline import *   # import sage library

_sage_const_30892 = Integer(30892); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_16 = Integer(16)
import os
os.environ['TERM'] = 'xterm-256color'

from pwn import *
from icecream import ic
from sage.all import *
from Crypto.Util.number import long_to_bytes
from Crypto.Cipher import AES
from hashlib import sha256
from icecream import ic


# io = process('python3 debug.py', shell=True, stderr=None)
io = remote('206.189.120.31', int(_sage_const_30892 ))

io.sendlineafter(b'> ', b'2')
io.sendlineafter(b'> ', b'1')

p = int(io.recvline().split(b'= ')[_sage_const_1 ])
g = int(io.recvline().split(b'= ')[_sage_const_1 ])
A = int(io.recvline().split(b'= ')[_sage_const_1 ])
B = int(io.recvline().split(b'= ')[_sage_const_1 ])

factors_pm1 = list(factor(p - _sage_const_1 ))
factors_pm1.sort()
q = factors_pm1[_sage_const_1 ][_sage_const_0 ]
r = factors_pm1[_sage_const_2 ][_sage_const_0 ]
ic(q, r)

F = GF(p)
F_B = F(B)
b = discrete_log(F_B, F(g))
ic(b)

ss = pow(A, int(b), p)

io.sendlineafter(b'> ', b'3')
flag_enc = bytes.fromhex(io.recvline(False).decode().split('= ')[_sage_const_1 ])

key = sha256(long_to_bytes(ss)).digest()[:_sage_const_16 ]
cipher = AES.new(key, AES.MODE_ECB)
pt = cipher.decrypt(flag_enc)
print(pt)

