

# This file was *autogenerated* from the file temp.sage
from sage.all_cmdline import *   # import sage library

_sage_const_16 = Integer(16); _sage_const_65537 = Integer(65537); _sage_const_1 = Integer(1)
from sage.all_cmdline import *
from Crypto.Util.number import getPrime, getRandomRange, isPrime, inverse, long_to_bytes, bytes_to_long
from icecream import ic


p = getPrime(_sage_const_16 )
ic(p)
q = getPrime(_sage_const_16 )
ic(q)
n = p*q
ic(n)
e = _sage_const_65537 

pt = bytes_to_long(b'sam')
ic(pt)

ct = pow(pt, e, n)

ic(ct)

l = (p-_sage_const_1 )*(q-_sage_const_1 )
ic(l)
d = pow(e, -_sage_const_1 , l)
ic(d)

pt_test = pow(ct, d, n)
ic(pt_test)

test = crt(p, q, int(ct % p), int(ct % q))
ic(test)

