

# This file was *autogenerated* from the file solution.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_13 = Integer(13); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_7 = Integer(7); _sage_const_256 = Integer(256)
from sage.all import *

def encrypt(msg, f):
    return ''.join(chr(f.substitute(c)) for c in msg)

P = PolynomialRing(ZZ, names=('x',)); (x,) = P._first_ngens(_sage_const_1 )
f = _sage_const_13 *x**_sage_const_2  + _sage_const_3 *x + _sage_const_7 

ct = open('./output.txt', 'r').read().strip()

subs = []
for i in range(_sage_const_256 ):
    subs.append(encrypt(bytes([i]), f))

pt = ''
for c in ct:
    pt += chr(subs.index(c))

print(pt)

