

# This file was *autogenerated* from the file substitution-cipher-ii.sage
from sage.all_cmdline import *   # import sage library

_sage_const_6 = Integer(6)
from string import ascii_lowercase, digits
CHARSET = "DUCTF{}_!?'" + ascii_lowercase + digits
n = len(CHARSET)

def encrypt(msg, f):
    ct = ''
    for c in msg:
        ct += CHARSET[f.substitute(CHARSET.index(c))]
    return ct

P = PolynomialRing(GF(n), names=('x',)); (x,) = P._first_ngens(1)
f = P.random_element(_sage_const_6 )

FLAG = open('./flag.txt', 'r').read().strip()

enc = encrypt(FLAG, f)
print(enc)

